module

public import STC.Core.Effect
public import STC.Core.Partial

/-!
# Generated reversible transformations

This companion records the finite transformation closure used by the global
metatheory. The closure is data and the commutation/recovery obligations are
separate predicates; no lifecycle continuation is hidden in this layer.
-/

universe u

namespace STC

@[expose] public section

section Closure

variable {S : Type u}

/-- A transformation is generated by identity, a supplied generator, or a
composition of already generated transformations. -/
inductive Generated (generators : Transformation S → Prop) : Transformation S → Prop
  | identity : Generated generators Transformation.identity
  | generator {t} : generators t → Generated generators t
  | twisted {later earlier} : Generated generators later →
      Generated generators earlier → Generated generators (Transformation.twisted later earlier)

theorem generated_identity (generators : Transformation S → Prop) :
    Generated generators Transformation.identity := .identity

theorem generated_generator (generators : Transformation S → Prop)
    {t : Transformation S} (h : generators t) : Generated generators t :=
  .generator h

theorem generated_twisted (generators : Transformation S → Prop)
    {later earlier : Transformation S} (hl : Generated generators later)
    (he : Generated generators earlier) :
    Generated generators (Transformation.twisted later earlier) :=
  .twisted hl he

/-- Exact forward equation for generated composition. -/
theorem generated_twisted_forward (later earlier : Transformation S) (x : S) :
    (Transformation.twisted later earlier).forward x =
      later.forward (earlier.forward x) := rfl

/-- Exact reverse equation for generated composition. -/
theorem generated_twisted_undo (later earlier : Transformation S) (x : S) :
    (Transformation.twisted later earlier).undo x =
      earlier.undo (later.undo x) := rfl

/-- A relation-parametric commutation witness for two transformations. -/
structure Commutes (R : RelSpec S) (later earlier : Transformation S) : Prop where
  forward : ∀ x, R.rel ((Transformation.twisted later earlier).forward x)
      ((Transformation.twisted earlier later).forward x)
  undo : ∀ x, R.rel ((Transformation.twisted later earlier).undo x)
      ((Transformation.twisted earlier later).undo x)

/-- A supplied closure law lifts generator commutation to the generated monoid.
The closure premise is explicit because generator commutation alone is not
stable under arbitrary transformations without compatibility hypotheses. -/
structure CommutationClosure (R : RelSpec S)
    (generators : Transformation S → Prop) where
  commute : ∀ {a b}, Generated generators a → Generated generators b → Commutes R a b

theorem generated_commutes (R : RelSpec S) (generators : Transformation S → Prop)
    (closure : CommutationClosure R generators)
    {a b : Transformation S} (ha : Generated generators a) (hb : Generated generators b) :
    Commutes R a b := closure.commute ha hb

end Closure

section Recovery

variable {S : Type u} {A : Type u}

/-- One successful operation with an explicit relation-level recovery law. -/
structure RecoveryOperation (R : RelSpec S) (A : Type u) where
  run : PartialOp S A
  recovers : OperationRecovers R run

/-- A selected earlier operation can be removed after an independent suffix.
The operation and suffix relations remain explicit rather than being inferred
from an opaque transformation monoid. -/
def SelectiveRemoval (R : RelSpec S) (_O : A → A → Prop)
    (before suffix : PartialOp S A) : Prop :=
  ∀ {input r s}, before input = some r → suffix r.state = some s →
    ∃ r', suffix input = some r' ∧ R.rel r'.state s.state

/-- A finite recovery package carries a removal witness for every selected
operation in a word. -/
structure RecoveryWord (R : RelSpec S) (A : Type u) where
  operations : List (PartialOp S A)
  recover : ∀ op ∈ operations, OperationRecovers R op
  remove : ∀ {op}, op ∈ operations →
    ∀ suffix, SelectiveRemoval R (fun _ _ => True) op suffix

end Recovery

end

end STC
